### ISSUE TITLE
Lua HistoryService API

### ISSUE THREAD

**Issue by Stephen-Martin** [orange451/AnarchyEngine#11]
As a user of Anarchy Engine
it would be nice to be able to access a HistoryService to manage change history
so that when a player attempts to undo after making a change with a plugin then it will be able to go back to the proper place

**Acceptance Criteria:**
- HistoryService allows for manual "snapshots"
- HistoryService also exposes `undo` and `redo` functions

**Comment by orange451** [comment]
First we need to make a History Service.

**Comment by orange451** [comment]
Created History Service, added lua-facing API for it. Also made undo/redo buttons in IDE. Slightly buggy with the current explorer. Might have to rewrite the explorer anyways...
